namespace Audio_Player
{
    [bindable]
    [default_interface]
    runtimeclass SongModel 
    {
        SongModel();
        String ImagePath;   
        String Title;
        Windows.Foundation.Uri SongPath;
        Windows.Media.Core.MediaSource MediaSource;
        Int32 Id;
    }
}
