namespace Audio_Player
{
    [bindable]
    [default_interface]
    runtimeclass SongModel 
    {
        SongModel(); 
        String Title;
        String Author;
        String SongPath;
        Windows.Media.Core.MediaSource MediaSource;
        Microsoft.UI.Xaml.Media.Imaging.BitmapImage Image;
        Int32 Id;
    }
}
