import "MainViewModel.idl";


namespace Audio_Player
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        MainViewModel MainViewModel{ get; };
    }
}
